const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.jumpthru,
		C3.Plugins.Button,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{CentrarEm: 0},
	{Sólido: 0},
	{Plataforma: 0},
	{player: 0},
	{cenario: 0},
	{Teclado: 0},
	{chao: 0},
	{instrucoes: 0},
	{basecristal: 0},
	{Sprite: 0},
	{bug: 0},
	{inventario: 0},
	{invInicio: 0},
	{telainicial: 0},
	{btinicio: 0},
	{Mouse: 0},
	{soma2numreos: 0},
	{Sprite2: 0},
	{indice: 0},
	{info: 0},
	{instrucao: 0},
	{instrucao2: 0},
	{PularAtravés: 0},
	{plataforma: 0},
	{Sprite4: 0},
	{Texto: 0},
	{bug2: 0},
	{seqerrada: 0},
	{seqcerta: 0},
	{infotexto: 0},
	{telavenceu: 0},
	{Botão: 0},
	{txtfechar: 0},
	{btnfechar: 0},
	{telaoutravez: 0},
	{barra: 0},
	{Sprite3: 0},
	{pontos: 0},
	{barra2: 0},
	{Sprite5: 0},
	{erro: 0},
	{barra3: 0},
	{erro2: 0},
	{Texto2: 0},
	{invX: 0},
	{invY: 0},
	{espY: 0},
	{count_inst: 0},
	{totalAcertos: 0},
	{totalErros: 0},
	{direcao: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	cenario: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	chao: class extends self.ISpriteInstance {},
	instrucoes: class extends self.ISpriteInstance {},
	basecristal: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bug: class extends self.ISpriteInstance {},
	inventario: class extends self.ISpriteInstance {},
	invInicio: class extends self.ISpriteInstance {},
	telainicial: class extends self.ISpriteInstance {},
	btinicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	soma2numreos: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	instrucao: class extends self.ITextInstance {},
	instrucao2: class extends self.ITextInstance {},
	plataforma: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	bug2: class extends self.ISpriteInstance {},
	seqerrada: class extends self.ISpriteInstance {},
	seqcerta: class extends self.ISpriteInstance {},
	infotexto: class extends self.ITextInstance {},
	telavenceu: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	txtfechar: class extends self.ITextInstance {},
	btnfechar: class extends self.ISpriteInstance {},
	telaoutravez: class extends self.ISpriteInstance {},
	barra: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	pontos: class extends self.ITextInstance {},
	barra2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	erro: class extends self.ITextInstance {},
	barra3: class extends self.ISpriteInstance {},
	erro2: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {}
}